language: scala

sudo: false

env:
  global:
    - TRAVIS_JDK=adopt@1.11.0-1
    - SCALA_212=2.12.10

matrix:
  fast_finish: true
  include:
    - env:
        - TRAVIS_JDK=adopt@1.8.0-232
        - SBT_CMD="scripted"

before_install:
  - nvm install node
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK
  - unset _JAVA_OPTIONS
  - export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

script:
  - sbt "$SBT_CMD"

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.cache/coursier/v1 -name "ivydata-*.properties" -print -delete
  - find $HOME/.ivy2/cache        -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt               -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba
